# Generated by Django 5.1.6 on 2025-03-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_asset_contract_po_pr_remove_document_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='PO',
        ),
        migrations.DeleteModel(
            name='PR',
        ),
    ]
