# Generated by Django 5.1.4 on 2024-12-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentApp', '0003_alter_incident_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'permissions': [('can_close_incident', 'Can change status to closed')]},
        ),
    ]
