# Generated by Django 5.1.6 on 2025-04-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentApp', '0005_alter_incident_options_remove_incident_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='incidentApp.category'),
            preserve_default=False,
        ),
    ]
