# Generated by Django 5.1.6 on 2025-04-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentApp', '0006_incident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='incidentApp.category'),
        ),
    ]
