# Generated by Django 5.1.4 on 2024-12-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('sap_asset_id', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('warranty_provider', models.CharField(max_length=100)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('amc_provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('create_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('attachment', models.FileField(upload_to='po_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('create_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('attachment', models.FileField(upload_to='pr_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='AssetIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_to', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.po'),
        ),
        migrations.AddField(
            model_name='po',
            name='pr_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.pr'),
        ),
    ]
