# Generated by Django 5.1.6 on 2025-02-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0002_contractattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IT Dept', max_length=255, unique=True)),
                ('location', models.CharField(default='OILHOUSE', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='OILHOUSE', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='end_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetApp.enduser'),
        ),
    ]
