# Generated by Django 5.1.4 on 2025-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0003_asset_unique_asset_type_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
