# Generated by Django 5.1.6 on 2025-02-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0003_enduser_asset_location_asset_end_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetApp.enduser'),
        ),
    ]
