# Generated by Django 5.1.6 on 2025-02-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0004_alter_asset_end_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='end_user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
    ]
