# Generated by Django 5.1.6 on 2025-02-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0004_asset_asset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_description',
            field=models.CharField(default='1111', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='po',
            name='pr_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetApp.pr'),
        ),
    ]
