# Generated by Django 5.1.6 on 2025-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0005_alter_asset_asset_description_alter_po_pr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
