# Generated by Django 5.1.6 on 2025-02-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0005_remove_asset_end_user_remove_asset_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndUser',
        ),
    ]
