# Generated by Django 5.1.6 on 2025-02-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0006_po_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Expired', editable=False, max_length=10)),
                ('pr_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetApp.pr')),
                ('wo_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetApp.po')),
            ],
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ids', models.TextField(help_text='Comma-separated email addresses')),
                ('days_before_expiry', models.PositiveIntegerField(help_text='Days before expiry to trigger notification')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.contract')),
            ],
        ),
    ]
