# Generated by Django 5.1.6 on 2025-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0007_enduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='location_status',
        ),
        migrations.AddField(
            model_name='enduser',
            name='location',
            field=models.TextField(default='IT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enduser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
    ]
