# Generated by Django 5.1.6 on 2025-02-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0009_alter_enduser_location_alter_enduser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='end_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetApp.enduser'),
        ),
    ]
