# Generated by Django 5.1.6 on 2025-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0011_remove_asset_amc_end_date_remove_asset_amc_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='smtp_sender_email',
            field=models.CharField(default='test@oilindia.in', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
