# Generated by Django 5.1.6 on 2025-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0012_smtpsettings_smtp_sender_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractattachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
