# Generated by Django 5.1.6 on 2025-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0013_contractattachment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnotification',
            name='enabled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text='Enable or disable notifications', max_length=3),
        ),
    ]
