# Generated by Django 5.1.6 on 2025-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0014_contractnotification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
