# Generated by Django 5.1.6 on 2025-03-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0015_asset_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
