# Generated by Django 5.1.6 on 2025-03-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0016_asset_amc_end_date_asset_amc_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('office', models.CharField(choices=[('OILHOUSE', 'OILHOUSE'), ('E&D Dte', 'E&D Dte'), ('Shastri Bhawan MoPNG', 'Shastri Bhawan MoPNG')], max_length=50)),
            ],
        ),
    ]
