# Generated by Django 5.1.6 on 2025-03-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0018_alter_asset_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='attachment',
        ),
    ]
