# Generated by Django 5.1.6 on 2025-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0019_remove_pr_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='attachment',
            field=models.FileField(default='psj.pdf', upload_to='pr_attachments/'),
            preserve_default=False,
        ),
    ]
