# Generated by Django 5.1.6 on 2025-03-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0020_pr_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='attachment',
        ),
    ]
