# Generated by Django 5.1.6 on 2025-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0021_remove_pr_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
