# Generated by Django 5.1.6 on 2025-03-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0023_remove_location_office_alter_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='location',
        ),
    ]
