# Generated by Django 5.1.6 on 2025-04-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0025_alter_enduser_name_poattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractnotification',
            name='contract',
        ),
        migrations.DeleteModel(
            name='SMTPSettings',
        ),
        migrations.DeleteModel(
            name='ContractNotification',
        ),
    ]
