# Generated by Django 5.1.6 on 2025-02-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetApp', '0002_contractattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.contract')),
            ],
        ),
    ]
