# Generated by Django 5.1.6 on 2025-02-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0002_contractattachment'),
        ('PlannedActivityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicactivitymaster',
            name='name',
            field=models.CharField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdHocActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetApp.contract')),
            ],
        ),
    ]
