# Generated by Django 5.1.6 on 2025-02-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0002_contractattachment'),
        ('PlannedActivityApp', '0002_periodicactivitymaster_name_adhocactivity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdHocActivity',
            new_name='AdHocActivityMaster',
        ),
    ]
