# Generated by Django 5.1.6 on 2025-02-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannedActivityApp', '0003_rename_adhocactivity_adhocactivitymaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('activity_completion_documents', models.FileField(blank=True, null=True, upload_to='planned_activity_docs/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodic_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlannedActivityApp.periodicactivitymaster')),
            ],
        ),
    ]
