# Generated by Django 5.1.6 on 2025-03-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0011_remove_asset_amc_end_date_remove_asset_amc_provider_and_more'),
        ('cartridge_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_qty', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='cartridge_stock.cartridgestock')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_qty', models.PositiveIntegerField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartridge_issues', to='AssetApp.asset')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cartridge_stock.cartridgestock')),
            ],
        ),
    ]
