# Generated by Django 5.1.6 on 2025-03-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetApp', '0011_remove_asset_amc_end_date_remove_asset_amc_provider_and_more'),
        ('cartridge_stock', '0002_cartridgeaddition_cartridgeissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridgeaddition',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridge_additions', to='AssetApp.po'),
        ),
    ]
