# Generated by Django 5.1.6 on 2025-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
